name: p2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  firebase_messaging: ^15.0.0
  overlay_support: ^2.1.0

  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_database: 11.3.10
  chat_bubbles: ^1.7.0
  
  go_router: ^17.0.0

  flutter_custom_clippers: ^2.1.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.8
  local_auth: ^2.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  google_maps_flutter: ^2.2.8
  geolocator: ^9.0.2
  permission_handler: ^11.3.1
  intl: ^0.20.2
  shared_preferences: ^2.1.1
  firebase_storage: ^12.4.10
  flutter_polyline_points: ^2.0.3
  firebase_app_check: ^0.3.2+10
  cloud_functions: ^5.0.3
  flutter_stripe: ^12.1.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

    integration_test:
    sdk: flutter
    
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
