name: p2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.2
  firebase_auth: ^5.6.2


  go_router: ^17.0.0

  flutter_custom_clippers: ^2.1.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.8
  local_auth: ^2.1.0
  qr_flutter: ^4.1.0
  google_maps_flutter: ^2.2.8
  geolocator: ^9.0.2
  permission_handler: ^11.3.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  google_ml_kit: ^0.20.0
  firebase_storage: ^12.4.10
  cloud_firestore: ^5.6.12


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
